/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg304application;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import pkg304application.database.DatabaseConnection;

/**
 *
 * @author toldham
 */
public class AchievementStatsPlayerForm extends javax.swing.JFrame {

    
    ResultSet rs;
    Statement stmt;
    String gName;
    double numOwnersWithAchievement;
    double numOwners;
    double percentOwners;
    
    /**
     * Creates new form AchievementStatsPlayerForm
     */
    public AchievementStatsPlayerForm() {
        initComponents();
    }

    public AchievementStatsPlayerForm(int aID, int gameID) {
         try {
            DatabaseConnection dbc = new DatabaseConnection();
            dbc.init();
            initComponents();
            stmt = dbc.getMyConnection().createStatement();
            
            showAchievement(aID, gameID);
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(GameInfoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void showAchievement(int aID, int gameID){
        try {
            String query = "select * from Achievement A, Game G where A.aID="
                    + aID +" and a.gameID=" + gameID; 
            rs = stmt.executeQuery(query);
            if (rs.next()){
                title.setText(rs.getString("aName"));
            }
            query = "select COUNT(*) As numplayers from HasWorkTowards H where H.aID=" + aID + " and H.isComplete=true";
            rs = stmt.executeQuery(query);
            if(rs.next()){
                numOwnersWithAchievement = Integer.parseInt(rs.getString("numPlayers"));
                numOwnersWithAchievementLabel.setText(rs.getString("numPlayers"));
            }
            query = "select COUNT(*) As numOwners from OwnsGame G where G.gameID=" + gameID;
            rs = stmt.executeQuery(query);
            if(rs.next()){
                numOwners = Integer.parseInt(rs.getString("numOwners"));
                System.out.println("Num Owners: " + numOwners);
                System.out.println("Num Owners with Achievement: " + numOwnersWithAchievement);
                if(numOwners == 0){
                    System.out.println("Zero owners");
                    percentOwners = 0;
                }
                else{
                    percentOwners = numOwnersWithAchievement/numOwners * 100;
                    System.out.println("Percent of owners:");
                    System.out.println(percentOwners);
                }
                
                percentPlayersLabel.setText(String.valueOf(Math.round(percentOwners)) + "%");
            }
            query = "select A.userName from HasWorkTowards H, Account A where H.aID=" + aID + " and H.isComplete=true and H.playerID = A.userID";
            rs = stmt.executeQuery(query);
            DefaultListModel userListModel = new DefaultListModel();
            while(rs.next()){
                userListModel.addElement(rs.getString("userName"));
            }
            userList.setModel(userListModel);
        } catch (SQLException ex) {
            Logger.getLogger(SearchReviewForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numPlayersLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        percentPlayersLabel = new javax.swing.JLabel();
        numOwnersLabel = new javax.swing.JLabel();
        numOwnersWithAchievementLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(483, 361));
        setResizable(false);
        setSize(new java.awt.Dimension(483, 361));
        getContentPane().setLayout(null);
        getContentPane().add(title);
        title.setBounds(256, 29, 161, 14);

        jLabel1.setFont(new java.awt.Font("Univers LT 45 Light", 0, 18)); // NOI18N
        jLabel1.setText("Achievement Stats:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 0, 157, 23);

        jLabel2.setFont(new java.awt.Font("Univers LT 45 Light", 0, 14)); // NOI18N
        jLabel2.setText("Achievement Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 29, 128, 18);

        jLabel3.setFont(new java.awt.Font("Univers LT 45 Light", 0, 14)); // NOI18N
        jLabel3.setText("Number of Players with Achievement:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 53, 241, 18);
        getContentPane().add(numPlayersLabel);
        numPlayersLabel.setBounds(481, 223, 139, 0);

        jLabel4.setFont(new java.awt.Font("Univers LT 45 Light", 0, 14)); // NOI18N
        jLabel4.setText("Percent of Game Owners with Achievement:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 79, 286, 18);
        getContentPane().add(percentPlayersLabel);
        percentPlayersLabel.setBounds(298, 79, 157, 14);
        getContentPane().add(numOwnersLabel);
        numOwnersLabel.setBounds(461, 79, 58, 0);
        getContentPane().add(numOwnersWithAchievementLabel);
        numOwnersWithAchievementLabel.setBounds(256, 53, 161, 18);

        userList.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        userList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        userList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 143, 469, 165);

        jLabel5.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        jLabel5.setText("Users with this Achievement:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 115, 161, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListMouseClicked
         try {
            if (evt.getClickCount() == 2){
                
                String selectedUser = userList.getSelectedValue();
                String queryStr = "Select userID from Account where userName='" + selectedUser + "'";
                rs = stmt.executeQuery(queryStr);
                rs.next();
                new SearchUserForm(Integer.parseInt(rs.getString("userID")),false).setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DeveloperForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AchievementStatsPlayerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AchievementStatsPlayerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AchievementStatsPlayerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AchievementStatsPlayerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AchievementStatsPlayerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numOwnersLabel;
    private javax.swing.JLabel numOwnersWithAchievementLabel;
    private javax.swing.JLabel numPlayersLabel;
    private javax.swing.JLabel percentPlayersLabel;
    private javax.swing.JLabel title;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
