/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg304application;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pkg304application.GameInfoForm.thisGameID;
import pkg304application.database.DatabaseConnection;

/**
 *
 * @author Connor
 */
public class EditAchievementForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    ResultSet rs;
    Statement stmt;
    String gName;
    
    public EditAchievementForm(){
        initComponents();
    }
    
    public EditAchievementForm(int aID, int gameID) {
        
        try {
            DatabaseConnection dbc = new DatabaseConnection();
            dbc.init();
            initComponents();
            stmt = dbc.getMyConnection().createStatement();
            showAchievement(aID, gameID);
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(GameInfoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        achievementDescription = new javax.swing.JTextPane();
        Description = new java.awt.Label();
        confirmButton = new javax.swing.JButton();
        label1 = new java.awt.Label();
        gameName = new java.awt.Label();
        totalDescription = new java.awt.Label();
        achievementName = new javax.swing.JTextField();
        totalNeeded = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(436, 355));

        achievementDescription.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(achievementDescription);

        Description.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        Description.setText("Achievement description:");
        Description.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescriptionMouseClicked(evt);
            }
        });

        confirmButton.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        label1.setText("Achievement name:");

        gameName.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        gameName.setText(gName);

        totalDescription.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        totalDescription.setText("Total Needed:");

        achievementName.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N

        totalNeeded.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmButton))
                    .addComponent(gameName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(achievementName))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(gameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(achievementName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(totalNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescriptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionMouseClicked

    private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseClicked
        // TODO add your handling code here:            
        try {            
            if (!validInput()){
                JOptionPane.showMessageDialog(null, "Please check achievement name is not empty and total needed is a positive number!", "Invalid information!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String update = "update Achievement set  aName='" + achievementName.getText() + "' , aDesc='" 
                    + achievementDescription.getText() + "' where totalNeeded= " +
                    Integer.parseInt(totalNeeded.getText()); 
            stmt.executeUpdate(update);
            this.setVisible(false);
            this.dispose();
            }
        catch (SQLException ex) {
            Logger.getLogger(ReviewForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmButtonMouseClicked

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Description;
    private javax.swing.JTextPane achievementDescription;
    private javax.swing.JTextField achievementName;
    private javax.swing.JButton confirmButton;
    private java.awt.Label gameName;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label totalDescription;
    private javax.swing.JTextField totalNeeded;
    // End of variables declaration//GEN-END:variables

    private void showAchievement(int aID, int gameID){
        try {
            String query = "select * from Achievement A, Game G where A.aID="
                    + aID +" and a.gameID=" + gameID; 
            rs = stmt.executeQuery(query);
            if (rs.next()){
            totalNeeded.setText(Integer.toString(rs.getInt("totalNeeded")));
            achievementDescription.setText(rs.getString("aDesc"));
            achievementName.setText(rs.getString("aName"));                     
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(SearchReviewForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validInput() {
        try{
            int num = Integer.parseInt(totalNeeded.getText());
            if (achievementName.getText().equals("")){
                return false;
            }    
            if (num < 0){
                return false;
            }
        } catch (NumberFormatException nfe){
            return false;
        }
        return true;
    }
    
}
