/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg304application;

import java.sql.*;
import java.text.DateFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import pkg304application.database.DatabaseConnection;

/**
 *
 * @author jinyou
 */
public class GroupInfoForm extends javax.swing.JFrame {

    /**
     * Creates new form GroupInfoForm
     */
    ResultSet rs;
    Statement stmt;
    Statement stmt2;
    int thisGroupID;
    
    public GroupInfoForm(String groupName, String groupDesc, int creatorUserID, String dateCreated){
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
               
        try {
            DatabaseConnection dbc = new DatabaseConnection();
            dbc.init();
            initComponents();
            stmt = dbc.getMyConnection().createStatement();
            stmt2 = dbc.getMyConnection().createStatement();
            String query = "select gID from FriendGroup where groupName = '" + groupName + "'";
            rs = stmt.executeQuery(query);
            rs.next();
            query = "select * from FriendGroup F where F.creatorUserID="+ MainForm.userID +" and F.gID="+ rs.getInt("gID");
            System.out.println(query);
            rs = stmt.executeQuery(query);
            if (!rs.next()){
                editGroupButton.setEnabled(false);
                deleteGroupButton.setEnabled(false);
            }
            showGroupInfo(groupName, groupDesc, creatorUserID, dateCreated);
            showUserList();
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(GameInfoForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupName = new javax.swing.JLabel();
        infoTab = new javax.swing.JTabbedPane();
        descriptionTab = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        userListTab = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        creatorName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateCreated = new javax.swing.JLabel();
        deleteGroupButton = new javax.swing.JButton();
        editGroupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(354, 451));

        groupName.setFont(new java.awt.Font("Univers LT 45 Light", 0, 18)); // NOI18N
        groupName.setText("jLabel1");

        infoTab.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N

        descriptionArea.setColumns(20);
        descriptionArea.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        descriptionArea.setRows(5);
        descriptionTab.setViewportView(descriptionArea);

        infoTab.addTab("Description", descriptionTab);

        userList.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        userList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        userList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListMouseClicked(evt);
            }
        });
        userListTab.setViewportView(userList);

        infoTab.addTab("User List", userListTab);

        jLabel1.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        jLabel1.setText("Creator:");

        creatorName.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        creatorName.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        jLabel3.setText("Date created:");

        dateCreated.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        dateCreated.setText("jLabel4");

        deleteGroupButton.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        deleteGroupButton.setText("Delete Group");
        deleteGroupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteGroupButtonMouseClicked(evt);
            }
        });

        editGroupButton.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        editGroupButton.setText("Edit Group");
        editGroupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editGroupButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(groupName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dateCreated))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(187, 187, 187)
                                            .addComponent(creatorName)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(editGroupButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteGroupButton))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(infoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(groupName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(creatorName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateCreated))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editGroupButton)
                    .addComponent(deleteGroupButton))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteGroupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteGroupButtonMouseClicked
        // TODO add your handling code here:
        String deleteStr;
        String selected = groupName.getText();
        try{
            String selectStr = "select * from FriendGroup F where F.groupName = '" + selected + "'";
            rs = stmt.executeQuery(selectStr);
            rs.next();
            deleteStr = "delete from FriendGroup where creatorUserID = "+ MainForm.userID +" and gID = "+rs.getInt("gID")+"";                              
            stmt.executeUpdate(deleteStr);
        } catch (SQLException ex) {
            Logger.getLogger(GameInfoForm.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }//GEN-LAST:event_deleteGroupButtonMouseClicked

    private void editGroupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editGroupButtonMouseClicked
        // TODO add your handling code here:
        String gName = groupName.getText();
        new EditGroupForm(gName).setVisible(true);
    }//GEN-LAST:event_editGroupButtonMouseClicked

    private void userListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2){
            String selectedUser = userList.getSelectedValue();
            String queryString = "Select A.userID from Account A where A.userName='" + selectedUser + "'";
                try {
                    rs = stmt.executeQuery(queryString);
                    if (rs.next()){
                        String check = "select * from Developer where developerID=" + rs.getInt("userID");
                        ResultSet rs2 = stmt2.executeQuery(check);
                        if (rs2.next()){
                            new SearchUserForm(rs.getInt("userID"), true).setVisible(true);
                        } else {
                            new SearchUserForm(rs.getInt("userID"), false).setVisible(true);
                        }
                    } else {
                        System.out.println("no user exists");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(GroupInfoForm.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_userListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creatorName;
    private javax.swing.JLabel dateCreated;
    private javax.swing.JButton deleteGroupButton;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JScrollPane descriptionTab;
    private javax.swing.JButton editGroupButton;
    private javax.swing.JLabel groupName;
    private javax.swing.JTabbedPane infoTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> userList;
    private javax.swing.JScrollPane userListTab;
    // End of variables declaration//GEN-END:variables
private void showGroupInfo(String g, String d, int cre, String date) {
        try {
            String queryStr = "Select gID from FriendGroup where groupName='" + g + "'";
            rs = stmt.executeQuery(queryStr);
            rs.next();
            thisGroupID = rs.getInt("gID");
            groupName.setText(g);
            descriptionArea.setText(d);
            dateCreated.setText(date);
            queryStr = "Select userName from Account where userID=" + cre;
            rs = stmt.executeQuery(queryStr);
            rs.next();
            creatorName.setText(rs.getString("userName"));
        } catch (SQLException ex) {
            Logger.getLogger(GameInfoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
}
private void showUserList() {
        try {
            String queryString = "Select A.userName from Account A, WithinGroup W where W.withinGroupID=" 
                                    + thisGroupID + " and  W.memberUserID = A.userID";
            rs = stmt.executeQuery(queryString);
            DefaultListModel userListModel = new DefaultListModel();
            while(rs.next()){
                userListModel.addElement(rs.getString("userName"));
            }
            userList.setModel(userListModel);
        } catch (SQLException ex) {
            Logger.getLogger(ProfileForm.class.getName()).log(Level.SEVERE, null, ex);
        }
}
}
