/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg304application;
import pkg304application.database.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jko
 */
public class NewGameForm extends javax.swing.JFrame {
    
    public ResultSet rs;
    public Statement stmt;
    /**
     * Creates new form NewGameForm
     */
    public NewGameForm() {
        try {
            initComponents();
            DatabaseConnection dbc = new DatabaseConnection();
            dbc.init();
            stmt = dbc.getMyConnection().createStatement();
            fillGenre();
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(NewGameForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameNameLabel = new javax.swing.JLabel();
        gameDescriptionLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameDescriptionField = new javax.swing.JTextArea();
        priceField = new javax.swing.JTextField();
        gameNameField = new javax.swing.JTextField();
        genreLabel = new javax.swing.JLabel();
        genreList = new java.awt.Choice();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(398, 317));

        gameNameLabel.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        gameNameLabel.setText("Game Name:");

        gameDescriptionLabel.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        gameDescriptionLabel.setText("Game Description:");

        priceLabel.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        priceLabel.setText("Price: ");

        gameDescriptionField.setColumns(20);
        gameDescriptionField.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        gameDescriptionField.setRows(5);
        jScrollPane1.setViewportView(gameDescriptionField);

        priceField.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N

        gameNameField.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N

        genreLabel.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        genreLabel.setText("Genre:");

        genreList.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N

        createButton.setFont(new java.awt.Font("Univers LT 45 Light", 0, 12)); // NOI18N
        createButton.setText("Create");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genreLabel)
                        .addGap(26, 26, 26)
                        .addComponent(genreList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gameNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gameDescriptionLabel)
                    .addComponent(createButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameNameLabel)
                    .addComponent(gameNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gameDescriptionLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genreLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(priceLabel)
                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(genreList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        try {
            // TODO add your handling code here:
            String gameName = gameNameField.getText();
            String gameDescription = gameDescriptionField.getText();
            int creatorID = MainForm.userID;
            double currentPrice = Double.parseDouble(priceField.getText());
            if (currentPrice < 0){
                JOptionPane.showMessageDialog(null, "Please insert positive values for price!", "Invalid value:", JOptionPane.INFORMATION_MESSAGE);
            }
            String genre = genreList.getSelectedItem();
            
            if (gameNameField.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter a game name!", "Missing Information:", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            int reply = JOptionPane.showConfirmDialog(null, "Confirm the information.", "Creating a new game:", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION){            
            
            String insertStr = "insert into Game(gName, gDescription, creatorID, currentPrice) values('" + gameName + "' , '" + gameDescription + "' , "
                    + creatorID + " , " + currentPrice + ")";
            stmt.executeUpdate(insertStr);
            
            String queryStr = "select gameID from Game where gName='" + gameName + "'";
            rs = stmt.executeQuery(queryStr);
            rs.next();
            
            insertStr = "insert into HasGenre(gameID, genre) values(" + Integer.toString(rs.getInt("gameID")) + ", '" + genre + "')";
            stmt.executeUpdate(insertStr);            
            
            this.setVisible(false);
            this.dispose();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(NewGameForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Please enter a valid price!", "Missing Information:", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
         
        
        
    }//GEN-LAST:event_createButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JTextArea gameDescriptionField;
    private javax.swing.JLabel gameDescriptionLabel;
    private javax.swing.JTextField gameNameField;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.JLabel genreLabel;
    private java.awt.Choice genreList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables

    private void fillGenre() {
        try {
            String queryStr = "Select * from Genre";
            ResultSet rs = stmt.executeQuery(queryStr);
            while (rs.next()){
              genreList.add(rs.getString("genre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(NewGameForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
