/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg304application;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import pkg304application.database.DatabaseConnection;

/**
 *
 * @author jko
 */
public class SearchAchievementForm extends javax.swing.JFrame {
    
    /**
     * Creates new form SearchAchievementForm
     */
    
    Statement stmt;
    ResultSet rs;
    
    public SearchAchievementForm(String achievementName) {
        try {
            DatabaseConnection dbc = new DatabaseConnection();
            dbc.init();
            stmt = dbc.getMyConnection().createStatement();
            initComponents();
            showInfo(achievementName);
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(SearchAchievementForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        achievementTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        achievementDesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        achievementTitle.setText("jLabel1");

        achievementDesc.setColumns(20);
        achievementDesc.setRows(5);
        jScrollPane1.setViewportView(achievementDesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(achievementTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(achievementTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea achievementDesc;
    private javax.swing.JLabel achievementTitle;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void showInfo(String achievementName) {
        try {
            String query = "select aDesc, aName, gName from Achievement A, Game G where G.gameID = A.gameID and G.gameID=" + GameInfoForm.thisGameID;
            System.out.println(query);
            rs = stmt.executeQuery(query);
            rs.next();
            achievementTitle.setText(rs.getString("gName") + "'s " + rs.getString("aName"));
            achievementDesc.setText(rs.getString("aDesc"));
            
        } catch (SQLException ex) {
            Logger.getLogger(SearchAchievementForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
